### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by johnhughbowen** [Barma-lej/halandroid#15]
My apologies, as im the only one I'm sure it's not a bug, but, I can't get the images to display in my lovelace card so everything is crunched up.
I've tried everything from using the full path name to using relative names. The images all seem to have the right permissions (read for everything) and the directories are rwx
The images below show the issue and that it is managing to pull the data without problem.

Has anyone got any ideas?

![image](https://user-images.githubusercontent.com/71754244/114935573-45699480-9e33-11eb-951d-bc6ab8245020.png)
![image](https://user-images.githubusercontent.com/71754244/114935788-86fa3f80-9e33-11eb-8446-1f7709d8d167.png)

**Comment by Barma-lej** [comment]
Save [this picture](https://raw.githubusercontent.com/Barma-lej/halandroid/master/www/mower/landroid_flower.png) to your www/mower/ folder
Did you change the name of lawnmower in App to **Mower**?

**Comment by Barma-lej** [comment]
Check your `configuration.yaml`
```
homeassistant:
  packages: !include_dir_named packages
```
Is there **one** entry `  packages:`?

Is exists the folder **packages** in your configuration folder?

Is there errors in home assistant log?

Is exists the folder packages in your configuration folder?

Is there errors in home assistant log?

**Comment by Micha031982** [comment]
Hi,
i have the same
![image](https://user-images.githubusercontent.com/19914654/156025081-ff7b51c1-c9d0-49bd-99ca-d467a0b9f9b1.png)
If i go to the Edit Mode
THe stats are shown
![image](https://user-images.githubusercontent.com/19914654/156025228-0ffd9178-8a87-425a-b7a2-84b4f8fc7798.png)
But THe Header picture is still not there 


UPDATE:
fixed it
Followed a old /wrong guide
There Te Folder for mower was www. it should be www

I also saw in the Yaml for the UI Card the Scedule Times
How can i change the scedule ?
