### ISSUE TITLE
Not all entities available with M500 Plus

### ISSUE THREAD

**Issue by r77s** [Barma-lej/halandroid#16]
Hi,
I current try to add the halandroid to my HA installation. And with my Worx Landroid M500 Plus I did't get alle entities. Only these few
![image](https://user-images.githubusercontent.com/18601077/118959137-52156700-b962-11eb-85bf-a7ff25d9aba8.png)

![image](https://user-images.githubusercontent.com/18601077/118953621-496e6200-b95d-11eb-9634-fe04bc94098f.png)

I hope I configured all correct. landroid_cloud is also added and configure like in the documention. Firmware is 3.24.

When I try to start the mover I get this error:
![image](https://user-images.githubusercontent.com/18601077/118959265-740ee980-b962-11eb-9d3a-ba68565a865f.png)

Or is the M500 plus not supported at the moment?

**Comment by Barma-lej** [comment]
Show me please all attributes of these 3 sensors

**Comment by ReneSattler** [comment]
> Show me please all attributes of these 3 sensors

![image](https://user-images.githubusercontent.com/18601077/118981573-c2c87d80-b97a-11eb-8a8f-694a60aa3df8.png)

![image](https://user-images.githubusercontent.com/18601077/118981847-189d2580-b97b-11eb-961c-eb8068145da4.png)
![image](https://user-images.githubusercontent.com/18601077/118981870-20f56080-b97b-11eb-92b1-9b46ca00d57d.png)
![image](https://user-images.githubusercontent.com/18601077/118982003-47b39700-b97b-11eb-9323-23b7f980451b.png)




Do you need this?

**Comment by Barma-lej** [comment]
Home Assistant Version?

**Comment by ReneSattler** [comment]
> Home Assistant Version?

Home Assistant 2021.5.5. Updated today to latest stable version.

**Comment by Barma-lej** [comment]
Do you have others landroid sensors in development tools?
If not, then:
1. Check `configuration.yaml`
```
homeassistant:
  packages: !include_dir_named packages
```
2. Check if file `packages/landorid.yaml` exists

**Comment by ReneSattler** [comment]
> Do you have others landroid sensors in development tools?
> If not, then:
> 
> 1. Check `configuration.yaml`
> 
> ```
> homeassistant:
>   packages: !include_dir_named packages
> ```
> 
> 1. Check if file `packages/landorid.yaml` exists

![image](https://user-images.githubusercontent.com/18601077/118984884-3f109000-b97e-11eb-8bd2-4a580a150dcc.png)
![image](https://user-images.githubusercontent.com/18601077/118985282-9d3d7300-b97e-11eb-92ef-dfc252e19efd.png)

Oh man. I found my problem. Double package was the problem. Now it works! 
Please close this issue.

**Comment by Barma-lej** [comment]
Double packages string

**Comment by Barma-lej** [comment]
> Oh man. I found my problem. Double package was the problem. Now it works!

Yes :)
Schönen Tag.

**Comment by ReneSattler** [comment]
> Double packages string

Yes I know. This happens when only copy and paste without thinking.
