### ISSUE TITLE
Feature Request: Deactivate "Not mowing when raining"  in continuous rain

### ISSUE THREAD

**Issue by r77s** [Barma-lej/halandroid#17]
Hi,
this is only a feature request and maybe also interesting for this package. :-)

Problem:
If you have a mowing time from 9 to 12 every day and you have the hole week raining weather. The mower runs the hole week not.

Maybe you can define days variable (example 3) for deactivating the "not mowing with rain". And activate this option again for example after 2 days normaly mowing.

I hope i explained the use case understandable.

**Comment by Barma-lej** [comment]
The goal of this project is to work with basic functions and show the lawnmower information in the Home Assistant.
Sorry, but I'm not sure if this fits into the scope of this project.

To solve the problem you described, I use **Auto Schedule** in **My Lawn** in the app.
