### ISSUE TITLE
Do not get all the sensors

### ISSUE THREAD

**Issue by Marra74** [Barma-lej/halandroid#18]
Hi! 

Have followed your manual (all steps) but i do not get all the sensors when i created lovelace card.
Edited the landroid.yaml (eng) and switched names for "sensor.landroid_mower_battery", "sensor.landroid_mower_error", "sensor.landroid_mower_status" and replaced mower with my name in the app. I also edited the card and replaced every name there also. But in the lovelacecard i only get "status", "battery". for an example sensor.landroid_wifi only gets an !, the same for sensor.landroid_dist... When i click on the card i have all status inclusive distance. What have i missed. Thank you for very good work!

**Comment by Barma-lej** [comment]
Please publish your `landroid.yaml`, lovelace card config and name of yours lawnmower

**Comment by Marra74** [comment]
The name is "bosse" and here is landroid.yaml and card.yaml files. Thanks!
[yaml-files.zip](https://github.com/Barma-lej/halandroid/files/6543982/yaml-files.zip)

**Comment by Barma-lej** [comment]
Which version of Home Assistant do you have?

**Comment by Marra74** [comment]
Home Assistant 2021.5.5

**Comment by Barma-lej** [comment]
Unfortunate can't find error. Make please a screenshot from **Developer tools** - **States** like this

![Screenshot 2021-05-26 115236](https://user-images.githubusercontent.com/34010886/119641059-8cc34780-be19-11eb-9366-43df46330454.png)

**Comment by Marra74** [comment]
Here it is...

---

I removed your screenshot. It has sn mac and id

**Comment by Barma-lej** [comment]
Check your `configuration.yaml`
```
homeassistant:
  packages: !include_dir_named packages
```
Is there **one** entry `  packages:`?

Is exists the folder **packages** in your configuration folder?

Is there errors in home assistant log?

**Comment by Marra74** [comment]
Yes only one entry

homeassistant:
  packages: !include_dir_named packages

Yes **packages** folder exists.

No errors in the log....

**Comment by Marra74** [comment]
Sorry it should be 

homeassistant:
packages: !include_dir_named package

**Comment by Marra74** [comment]
Now i found the problem.
I have several other entrys under homeassistant: and **packages: !include_dir_named packages** had 2 spaces to much so it became a subentry...Sorry my misstake. Now it works perfect! Thanks for your help.

**Comment by Barma-lej** [comment]
No problem. Enjoy 😊
