### ISSUE TITLE
Not all entities available

### ISSUE THREAD

**Issue by simistef** [Barma-lej/halandroid#20]
Hi there,

I have followed all the installation instructions and in the end i got into this stage with missing components. I can however start, stop, send home and can see the battery charging, etc. But missing the dashboard entities:

<img width="582" alt="Screenshot 2021-06-23 at 15 32 49" src="https://user-images.githubusercontent.com/2674401/123097505-e0d14400-d438-11eb-9f93-7972d1aa0e91.png">

Have not much an idea on how i could fix this, as i have no errors in the log file and all configuration files are looking good as per instructions.

Here is the system info:

<img width="582" alt="Screenshot 2021-06-23 at 15 38 51" src="https://user-images.githubusercontent.com/2674401/123097808-27bf3980-d439-11eb-94e4-4244bb7872d4.png">

Any help would be much appreciated

**Comment by Barma-lej** [comment]
[Do you have read that already?](https://github.com/Barma-lej/halandroid/issues/18)

**Comment by simistef** [comment]
Yes, i did and i think that everything looks fine to me.

Here are the configuration files
[Archive.zip](https://github.com/Barma-lej/halandroid/files/6714442/Archive.zip)

and the screenshot from Developer tools:

<img width="774" alt="Screenshot 2021-06-25 at 10 43 22" src="https://user-images.githubusercontent.com/2674401/123389527-a683b600-d5a2-11eb-9011-c64a230ff987.png">

**Comment by Barma-lej** [comment]
Do you have dir packages in your homeassistant dir?

**Comment by simistef** [comment]
Yes, i do

<img width="438" alt="Screenshot 2021-06-25 at 11 55 12" src="https://user-images.githubusercontent.com/2674401/123399521-5eb65c00-d5ad-11eb-9d14-0ae12fab063a.png">

**Comment by Barma-lej** [comment]
Be careful and compare:
Your `configuration.yaml`:
```
homeassistant:
    packages: !include_dir_named packages
```
should be:
```
homeassistant:
  packages: !include_dir_named packages
```

**Comment by simistef** [comment]
Hmmm, changed it. Hope ok now.
<img width="506" alt="Screenshot 2021-06-25 at 13 29 44" src="https://user-images.githubusercontent.com/2674401/123411749-77c50a00-d5b9-11eb-8312-e0a99720b1e9.png">

But still. Problem remains...
<img width="504" alt="Screenshot 2021-06-25 at 13 29 26" src="https://user-images.githubusercontent.com/2674401/123411828-8f9c8e00-d5b9-11eb-955e-a26776f78d36.png">

Also did restart of entire system not just Home Assistant.

**Comment by Barma-lej** [comment]
What is in the log?

**Comment by simistef** [comment]
Here is the log from home assistant

[logs.txt](https://github.com/Barma-lej/halandroid/files/6715676/logs.txt)

**Comment by Barma-lej** [comment]
## Requirements

1. **Home Assistant** version 2021.4 or above

**Comment by simistef** [comment]
oh. i see...
means that i need to wait for another update to home assistant core for synology

Many many thanks for your support !

**Comment by Barma-lej** [comment]
You can use [this version of landroid.yaml with old sensor configuration](https://github.com/Barma-lej/halandroid/blob/a734342de3ad201b47b225c2a1f7f2b301c22fa2/packages/landroid.yaml)

**Comment by simistef** [comment]
thanks ! didn't not work ...

i got this error in the logs:

Logger: homeassistant.config
Source: config.py:415 
First occurred: 17:50:04 (1 occurrences) 
Last logged: 17:50:04

> Invalid config for [sensor.template]: template value is None for dictionary value @ data['sensors']['landroid_ip']['value_template']. Got None template value is None for dictionary value @ data['sensors']['landroid_mac']['value_template']. Got None template value is None for dictionary value @ data['sensors']['landroid_sn']['value_template']. Got None. (See /volume1/@appstore/homeassistant/var/config/packages/landroid.yaml, line 69). Please check the docs at https://www.home-assistant.io/integrations/template

**Comment by Barma-lej** [comment]
Do you have in your `secrets.yaml` these three entries?
```
landroid_ip: YOUR_LANDROID_IP_ADDRESS_IF_YOU_NEED_IT_OR_''
landroid_sn: LANDROID_SERIAL_NUMBER_IF_YOU_NEED_IT_OR_''
landroid_mac: LANDROID_MAC_ADDRESS_IF_YOU_NEED_IT_OR_''
```
If not then remove this  from `landroid.yaml`
```
      landroid_ip:
        friendly_name: IP Address
        value_template: !secret landroid_ip
        icon_template: mdi:ip-network

      landroid_sn:
        friendly_name: Serial number
        value_template: !secret landroid_sn
        icon_template: mdi:numeric

      landroid_mac:
        friendly_name: MAC-Address
        value_template: !secret landroid_mac
        icon_template: mdi:barcode
```

**Comment by simistef** [comment]
i do, but they have no values. should i remove them completely from secrets.yaml and landroid.yaml ?

<img width="695" alt="Screenshot 2021-06-26 at 07 20 17" src="https://user-images.githubusercontent.com/2674401/123501637-1b142e80-d64f-11eb-80fe-a82859947784.png">

**Comment by simistef** [comment]
It worked ! Removed them from secrets and landroid yaml files !

<img width="338" alt="Screenshot 2021-06-26 at 08 09 23" src="https://user-images.githubusercontent.com/2674401/123502541-d8098980-d655-11eb-8e7a-a6bf68bdb095.png">

Many many thanks for your support !

**Comment by simistef** [comment]
Hey, it's me again ....
Because i updated my Synology to DSM 7, i had to update home assistant as well. Good thing now, that is the latest version Home Assistant 2021.6.6

However the errors are again back ... and whatever i did, i was unable to fix them:

<img width="369" alt="Screenshot 2021-07-06 at 15 05 54" src="https://user-images.githubusercontent.com/2674401/124597103-b6857a80-de6b-11eb-9a10-efb1f5d79850.png">

Landroid cloud entities like time mowing, pause, stop, etc are fine and displaying correctly. But those fold-entity-rows are not.

Would much appreciate if you can check my config files again. I did took out the ip, mac entities, but nothing
[Archive.zip](https://github.com/Barma-lej/halandroid/files/6769874/Archive.zip)

Thanks in advance!

**Comment by Barma-lej** [comment]
[Install fold-entity-row](https://github.com/thomasloven/lovelace-fold-entity-row)

**Comment by simistef** [comment]
I do have it installed:

<img width="516" alt="Screenshot 2021-07-06 at 18 00 51" src="https://user-images.githubusercontent.com/2674401/124622932-33245300-de84-11eb-8737-0005f50f663c.png">

but i got this error in the logs:

<img width="516" alt="Screenshot 2021-07-06 at 18 01 05" src="https://user-images.githubusercontent.com/2674401/124622975-3b7c8e00-de84-11eb-9fd2-7352ff6991e8.png">

**Comment by Barma-lej** [comment]
Is it iOS? Also install add-on [card-tools](https://github.com/thomasloven/lovelace-card-tools)

[This error is here](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#some-common-error-messages)

**Comment by simistef** [comment]
Thanks again Barma-lej ! It was the card-tools that needed to be installed apparently. Super appreciate you help !
