### ISSUE TITLE
Utilizing multizone and distances which came I Landroid cloud add-on in version 1.6.3

### ISSUE THREAD

**Issue by jascdk** [Barma-lej/halandroid#26]
Hi .

How do I use the new features, which came in the landroid cloud custom component from mtrab? 

https://github.com/MTrab/landroid_cloud/releases

it should be possible to do as mentioned here 

https://github.com/MTrab/landroid_cloud/pull/47

**Comment by fanningert** [comment]
Check my comment in this issue.
https://github.com/Barma-lej/halandroid/issues/31#issuecomment-950297924

**Comment by Barma-lej** [comment]
Package updated with new features
