### ISSUE TITLE
Landroid bladetime not reseting 

### ISSUE THREAD

**Issue by Fettkeewl** [Barma-lej/halandroid#28]
Hi 
I went to reset my blade time stats in Landroid app thinking it would sync to my instance of your code. Sadly it does not. Worked up 6h on new blades and the old blade time still shows. Tried manually changing to 0 and it synced back to the wrong bladetime.

Am I doing it wrong?
![SmartSelect_20210822-200437_Home Assistant](https://user-images.githubusercontent.com/25577040/130365406-ad5b54d6-53fc-4f99-bb46-1afae1c1b948.jpg)
![Screenshot_20210822-200504_Landroid](https://user-images.githubusercontent.com/25577040/130365407-08476a77-74b3-493b-b28a-a5817c573b9f.jpg)

**Comment by Barma-lej** [comment]
This issue is discussed [here](https://github.com/MTrab/landroid_cloud/issues/62)
