### ISSUE TITLE
Change how often it updates status?

### ISSUE THREAD

**Issue by DLTKsorenbache** [Barma-lej/halandroid#29]
It seems to me that it updates the status each 30 minutes or so. Is it possible to do it more often? 

<img width="1081" alt="Screenshot 2021-10-04 at 23 04 04" src="https://user-images.githubusercontent.com/6010048/135927088-2ea21718-0cfd-4fe2-b2a1-96c41119e456.png">

**Comment by MTrab** [comment]
The integration forces updates every 30 minutes, if the device haven't reported anything before.
It's not a good idea to force updates more often, as you'd risk being banned by the Worx API.
