### ISSUE TITLE
Issue with mower name

### ISSUE THREAD

**Issue by OhSoGood** [Barma-lej/halandroid#3]
First device added after first installation of HomeAssistant. That has been a tough time!

I first couldn't get any information from sensor and I finally realized that your hardcoded the name you have to your mower, m500 (maybe the default one?) into each and any sensor name in both landroid.yaml and add_to_lovelace.yaml

Thus, if one has a mower called 'mymower', he should replace all 'sensor.landroid_m500' by 'sensor.landroid_mymower'.
I guest your package could be improved and that name retrieved by http and not hardcoded.

**Comment by Barma-lej** [comment]
Here is explanation of this https://github.com/MTrab/landroid_cloud#entities--services

The name of the sensors is set by integration.

**Comment by OhSoGood** [comment]
Hi,
Indeed, that means the mower name is retrieved from the cloud and should not be hardcoded. In landroid_cloud, the corresponding code is `info["name"] = util_slugify(f"{DEFAULT_NAME}_{self._client.name}")` , so halandroid should do the same, doesn't it?

**Comment by Barma-lej** [comment]
Yes, my landroid has a name in the app "m500", and therefore the sensors have a names:
```
sensor.landroid_m500_battery
sensor.landroid_m500_error
sensor.landroid_m500_status
```

**Comment by OhSoGood** [comment]
On mine, by default it's WR106SI (it's the same but previous model of the M500, before 2018). There could be also the M1000, the L2000. So to hardcode m500 in landroid.yaml and add_to_lovelace.yaml would make the code incompatible with all these. Do you think you could make your code retrieve dynamically the mower name?

**Comment by Barma-lej** [comment]
I get data from the sensors that  creates Landroid Cloud integration. To change the name of the sensors, you need to change the name of the robot in the application or replace it in package
