### ISSUE TITLE
Translatations in landroid.yaml not used?

### ISSUE THREAD

**Issue by OhSoGood** [Barma-lej/halandroid#4]
Hi again
I translated the word in the configure section at the end of landroid.yaml, but all the occurrences which are hard-coded in add_to_lovelace.yaml are not replaced. Is that a bug?

**Comment by Barma-lej** [comment]
These are hardcoded names in Lovelace.
I am now rewriting the package and making the default configuration in english

**Comment by OhSoGood** [comment]
Fine! I can provide the French translation once it's done.
