### ISSUE TITLE
Can´t get this to work

### ISSUE THREAD

**Issue by ghost** [Barma-lej/halandroid#41]
Hi
Thanks a lot for all your work. I followed your install instructions manualy and via HACS but get always the same errors. Since there are now errors up to the point form MTrab I post this here

Most errors say
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

[548149954208] Error handling message: Unknown error
18:22:07 – (FEHLER) Home Assistant WebSocket API (benutzerdefinierte Integration)
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
18:22:07 – (FEHLER) Worx Landroid Cloud (benutzerdefinierte Integration)
Mower set rain delay and time extension: Error executing script. Unexpected error for call_service at pos 1: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
18:22:07 – (FEHLER) Skript (benutzerdefinierte Integration)

Can you give me a hint?
Really appreceated.
Thanks Chris

**Comment by Barma-lej** [comment]
Do you have sensors: `sensor.landroid_mower_battery`, `sensor.landroid_mower_error`, `sensor.landroid_mower_status`?

**Comment by ghost** [comment]
Yes. Different names but sensors are there

Sent from mobile device. Please excuse shortness of message and typos.
Best regards
Christoph

**Comment by Barma-lej** [comment]
If you have different name of your lawnmower then you need rename all the names of these sensors (`sensor.landroid_mower_battery`, `sensor.landroid_mower_error`, `sensor.landroid_mower_status`) in the files __package/landroid_de.yaml__, __package/landroid_LANGUAGE_CODE.yaml__ and in new __Lovelace card__
or
Change the name of lawnmower in App to Mower

[See Installation Number 6](https://github.com/Barma-lej/halandroid#installation)

**Comment by ghost** [comment]
All names are correct and several entities like battery are correct but not all. Some are missing like distance etc. See screenshot
![grafik](https://user-images.githubusercontent.com/100223819/162564442-afc29efb-8f08-4008-84ec-bde5c315b8ba.png)
When pressing the start button, the error comes up and nothing will happen. Could it be an error from Websocket API?

**Comment by Barma-lej** [comment]
1. What is name of your lawnmower?
2. Did you make changes in `landroid.yaml`,  `landroid_de.yaml` and in your dashboard card?

**Comment by ghost** [comment]
Ok, I forgot to make changes to the two files. Fixed it and now it is working like charm.
Sorry for bothering and really appreceate your support!
Many thanks!!!
