### ISSUE TITLE
Translation - Polish language

### ISSUE THREAD

**Issue by Erestes** [Barma-lej/halandroid#43]
These are my first steps in github, I wanted to contribute by adding the Polish translation so I've prepared it and made it available here: 
[https://github.com/Erestes/PL-translation-for-halandroid/tree/main](https://github.com/Erestes/PL-translation-for-halandroid/tree/main)

@Barma-lej  Not sure whether or not it is the right way of doing it - feel free to just copy/paste the file to your repo and let me know whether I should remove the file/folder from that repository afterwards. 

Cheers.

**Comment by Barma-lej** [comment]
1. Open the file [from here](https://github.com/Barma-lej/halandroid/blob/master/lang/landroid_pl.yaml)
2. Click a pen
![Screenshot 2022-04-09 205702](https://user-images.githubusercontent.com/34010886/162588025-71f9d66b-22a6-4d6c-8b32-7497c5fd39a2.jpg)
3. Edit file in your repository
4. Create new pull request
![Screenshot 2022-04-09 210414](https://user-images.githubusercontent.com/34010886/162588201-0f797dcd-981e-45b1-9899-c598e31c0c4b.jpg)

Can you still add translate for car_pl.yaml [from here](https://github.com/Barma-lej/halandroid/blob/master/lovelace/card_pl.yaml)?

**Comment by Erestes** [comment]
Done, thanks for the hints.

**Comment by Barma-lej** [comment]
Yes, the link to car_pl.yaml was broken. I changed it to https://github.com/Barma-lej/halandroid/blob/master/lovelace/card_pl.yaml
The file is empty. You can copy content from card.yaml https://github.com/Barma-lej/halandroid/blob/master/lovelace/card.yaml

**Comment by Erestes** [comment]
Done, not sure why it was blank previously. Anyway I hope it's okay now.

**Comment by Barma-lej** [comment]
👍 Super thanks
