### ISSUE TITLE
the part after the picture element disappears after leaving edit mode of love lace editor 

### ISSUE THREAD

**Issue by krammerj2486** [Barma-lej/halandroid#48]
I have the problem that after pasting the lovelace code into the manual card everything is shown (in the edit mode). After leaving the edit mode of the lovelace editor only the picture element is shown. The Part with configuration and multizone... disappears. I hope you can help me...

**Comment by krammerj2486** [comment]
![image](https://user-images.githubusercontent.com/47688625/164097886-d80fd20f-24a2-4658-b194-b02ccf9d39df.png)

**Comment by krammerj2486** [comment]
![image](https://user-images.githubusercontent.com/47688625/164098538-0e98c373-5502-4f3a-b0d2-c4ad1f9a4b97.png)

**Comment by Barma-lej** [comment]
You can try to click on **i** and **clock** icons...

**Comment by krammerj2486** [comment]
Yes thank you, that does the trick 🤦‍♂️

best wishes

     Jürgen

Am 19.04.2022 um 23:46 schrieb Barma-lej ***@***.***>:

﻿

You can try to click on i and clock icons...
