### ISSUE TITLE
do not get values...

### ISSUE THREAD

**Issue by michapr** [Barma-lej/halandroid#49]
Hi,
thanks for this plugin!

I have installed as described (renamed even my mover) so that have now the 3 sensors like "sensor.landroid_mover_status" etc.
Can see in status sensor the changing attributes - so all seems to be fine.

Adding your card - I see only "Unbekannt" , "0,0 km" etc.

If I check the properties in card I see as sample "sensor.mower_distance" for the value - but as far as I understand this is should be an attribute, right?
What I made wrong? what is missing?
![grafik](https://user-images.githubusercontent.com/11854556/164504153-33fe611f-0894-4038-a941-42d5e11cb483.png)

Thank you for your help!

**Comment by Barma-lej** [comment]
1. In configuration.yaml add string packages: !include_dir_named packages:
```
homeassistant:
  packages: !include_dir_named packages
```
Did you do it?

**Comment by michapr** [comment]
yes,... sorry my mistake. I had a name "Mover" - instead of "Mower" .. it could not work :(

But found other issue - will open a new one (regarding zones)
