### ISSUE TITLE
Bug: wrong 'stop' command called from landroid_cloud

### ISSUE THREAD

**Issue by OhSoGood** [Barma-lej/halandroid#5]
To stop the owner and make it go home, landroid.yaml calls landroid_cloud.stop but that doens't exist. It's landroid_cloud.pause. Just replace it in landroid.yaml line 271 in script/landroid_stop/sequence

**Comment by Barma-lej** [comment]
Thank you. In further release will used it as landroid_cloud.home service

**Comment by Barma-lej** [comment]
Fixed in the new version
