### ISSUE TITLE
missing zones for L1000

### ISSUE THREAD

**Issue by michapr** [Barma-lej/halandroid#50]
I have connected - all looks fine, but zones for L1000 are not visible.

Maybe the syntax was changed?
this is from DeskApp:
![grafik](https://user-images.githubusercontent.com/11854556/164527010-74912916-93e3-4dd2-b369-2113e7f14e9e.png)
this from HA:
![grafik](https://user-images.githubusercontent.com/11854556/164527218-fe5e67b2-d01d-40f3-8f3d-227486d0ab0d.png)

And - I did't found the time planer - where it is located?
This is also a new one (if I remember right) - here I can define two time windows for every day:
(again from DeskApp):
![grafik](https://user-images.githubusercontent.com/11854556/164527852-c64546e1-707a-4a29-acea-2fea99ae9874.png)

THANKS!

**Comment by michapr** [comment]
This are my MQTT data:
`{
  "cfg":{"id":42762,"lg":"it",
    "tm":"16:14:18","dt":"22/04/2022",
    "sc":{"m":0,"distm":0,"ots":{"bc":0,"wtm":0},"p":0,
      "d":[["00:00",0,0],["07:00",360,1],["07:00",600,0],["07:00",300,0],["07:00",600,0],["07:00",600,0],["07:00",360,0]],
      "dd":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["15:00",300,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]},
    "cmd":0,
    "mz":[2,39,128,181],"mzv":[0,1,2,3,0,1,2,3,0,1],
    "rd":180,
    "sn":"2021xxxxxxxxxxxxxxxxxx",
    "al":{"lvl":0,"t":60},"tq":0},
  "dat":{
    "mac":"xxxxxxxxxxxx",
    "fw":3.26,"fwb":1,
    "bt":{"t":14.9,"v":18.79,"p":96,"nr":9,"c":0,"m":0},
    "dmp":[-6.0,7.0,67.5],
    "st":{"b":1100,"d":17180,"wt":1177,"bl":474},
    "ls":7,"le":0,"lz":0,
    "rsi":-66,"lk":0,"act":1,"tr":0,"conn":"wifi",
    "rain":{"s":0,"cnt":0},"time":{"r":132,"l":132}
}}`

Maybe it can help...

**Comment by MTrab** [comment]
Please create issue at https://github.com/mtrab/landroid_cloud
Currently landroid_cloud integration doesn't pull 2nd schedule and zone config - you hare only able to set zone config as it is right now.

**Comment by MTrab** [comment]
This should be fixable by @barma-lej, as the zone and schedule info are present in v2

**Comment by Barma-lej** [comment]
Wait a little 🙂. I work now with a new version of landroid-card.
