### ISSUE TITLE
Many entities missing

### ISSUE THREAD

**Issue by markdswan926** [Barma-lej/halandroid#55]
I have followed the install instructions a number of times without success. Any pointers on this issue?
![image](https://user-images.githubusercontent.com/60292148/170890667-c65af469-248c-40c5-8c6e-9a464c5bcf38.png)

**Comment by aherking** [comment]
I think this is related to the latest Update of the Landroid integration. They moved to vacuum entity, the card.yaml has to be adjusted.

**Comment by DC-MORTR** [comment]
Guess your mower isn't named `mower` in your app?!

**Comment by DC-MORTR** [comment]
See step 6 here: https://github.com/Barma-lej/halandroid#installation

**Comment by aherking** [comment]
It's called "mower" in my app, and it worked before Updating to HA-Landroid 2.0 perfectly, so i think this is related to the update.

**Comment by Barma-lej** [comment]
The package doesn't work with HA-Landroid 2.0 yet. I'll made new package soon 🙄

**Comment by aherking** [comment]
Thanks for your comment, no need to hurry just wanted to make sure I'm not misconfigurating somehting. Appreciate your work a lot!

**Comment by MTrab** [comment]
@aherking that's actually mentioned in the release notes 🤷🏼‍♀️

**Comment by Barma-lej** [comment]
The package is adapted for landroid cloud integration 2
