### ISSUE TITLE
Update Landroid Cloud to Version 2.0.1

### ISSUE THREAD

**Issue by TheRealWiesel87** [Barma-lej/halandroid#57]
Hi,

after the Landroid Cloud Update to Version 2.0.1 there are the following Problems:

- Entity not available: sensor.landroid_mover_status
- Entity not available: sensor.landroid_mover_error
- Entity not available: sensor.landroid_mover_battery
![Mover1](https://user-images.githubusercontent.com/106491851/171341193-11471753-41a7-48e8-9de6-1a47a107bd69.jpg)
![Mover2](https://user-images.githubusercontent.com/106491851/171341202-c28e48db-ef37-4a76-ae0b-99fdd331d1f6.jpg)

**Comment by Diddlik** [comment]
Yes, it was a breaking change. But I found no information how to move to new verison

**Comment by puttemanp** [comment]
You can downgrade to the previous version. Just go to HACS, integrations, landroid cloid. Click on the 3 dots and then 'redownload'. Select the previous version and your card will work again.
You will get a notification that an update for Landroid Cloud is ready, but don't download until the custom card has been updated.

**Comment by Barma-lej** [comment]
The package is adapted for landroid cloud integration 2
