### ISSUE TITLE
input_number.mower_timeextension - missspelled in helper definition

### ISSUE THREAD

**Issue by Papi77** [Barma-lej/halandroid#59]
Hi,
Just installed the new integration version for Landroid - noticed a typo in configuration of one of the config parameters.

In helpers the entity is setup as:
input_number.mower_timeextension
but in the card it is referenced as:
input_number.mower_time_extension

Correcting the helper name fixes the issue.

Regards,

**Comment by Barma-lej** [comment]
Thank you. Fixed
