### ISSUE TITLE
Copy of my German to English translation

### ISSUE THREAD

**Issue by rosscullen** [Barma-lej/halandroid#6]
Hi @Barma-lej 
Once again, great job on Halandroid! Below is my translation from German to English for anyone that may be looking for it.

Simply find and replace the words (using something like Notepad++) in your landroid.yaml file (packages folder) and in your "add_to_lovelace.yaml" file (or your Home Assistant Lovelace Raw Configuration file, if you have already the code added to Lovelace).

| German  | English |
| ------------- | ------------- |
| Akku Status  	| Battery Status |
| Akkuladung  	| Battery |
| Akkuspannung  	| Battery Voltage |
| Akkustatus  	| Battery Status |
| Akkutemperatur  	| Battery Temperature |
| Aktualisiert seit  	| Last Update |
| Arbeitszeit  	| Total Time |
| Batteryen  	| Battery Charge Cycles |
| Benachrichtigung  	| Notification |
| Entlädt  	| Discharging |
| Fehler  	| Error |
| Ges. Distanz  	| Total Distance |
| Gesamte Arbeitszeit  	| Total Time (hours) |
| Gesamte Distanz  	| Total Distance |
| Gieren/Рысканье  	| Yaw |
| Information  	| Information |
| IP-Adresse  	| IP Address |
| Klingenarbeitszeit  	| Blade Time |
| Lädt  	| Charging |
| MAC-Adresse  	| MAC Address |
| Mähen  	| Mow |
| Mähen beenden  	| Stop Mowing |
| Mähen pausieren  	| Pause Mowing |
| Mäheroboter  	| Robotic lawnmower |
| Mähplan  	| Schedule |
| Nicken/Тангаж  	| Pitch |
| Regenverzögerung  	| Rain Delay |
| Rollen/Крен  	| Roll |
| Seriennummer  	| Serial Number |
| Stop & Nach Hause fahren  	| Stop & Drive Home |
| WLAN Qualität  	| WIFI Quality |
| Zeiterhöhung  	| Time Increase |

PS: take care when finding and replacing the word "Mähen" as it exists a few time as part of 2 words.

**Comment by Barma-lej** [comment]
Thank you. I am now rewriting the package and will definitely add your translation as soon as it is ready

**Comment by Barma-lej** [comment]
Added in new version. Default language is now English
