### ISSUE TITLE
landroid_cloud v2.*

### ISSUE THREAD

**Issue by lordleicester** [Barma-lej/halandroid#63]
halandroid depends on the work of @MTrab and https://github.com/MTrab/landroid_cloud

according to the change logs an upgrade to landroid_cloud >v2.* breakes the halandroid-plugin:
https://github.com/MTrab/landroid_cloud/releases
this matchees with my expirience, since after the update the plugin no longer works.

Do I need to reinstall the haldriod? or are changes nessessary?
Can you please have a look into this issue?

Thanks!

**Comment by MTrab** [comment]
Did you see #57??

**Comment by Barma-lej** [comment]
Try new card

https://github.com/Barma-lej/landroid-card

**Comment by lordleicester** [comment]
I am totally sorry! I did miss that!
Thanks to both of you!
