### ISSUE TITLE
Missing Informations - Some Unknowns

### ISSUE THREAD

**Issue by Marow** [Barma-lej/halandroid#71]
Hi,

any ideas why i have so much unknown infos (Unbekannt)?
Also under "Mähen" on the Top left, i just have [object object]

Last update was 01.01.1970?

![image](https://user-images.githubusercontent.com/2269012/191906960-883cbf11-2c3e-4d5e-8776-75a4beed0f17.png)

But i can see the pitch in the `vacuum.mower`
![image](https://user-images.githubusercontent.com/2269012/191917412-f0b25cdb-55a4-4ef8-a921-de05c7e38533.png)

And as you can see,  the battery also is available on the card...

**Comment by Barma-lej** [comment]
[Don't work with Landroid Cloud > 2.0.3](https://github.com/Barma-lej/halandroid#dont-work-with-landroid-cloud--203)
