### ISSUE TITLE
Error displaying Information

### ISSUE THREAD

**Issue by Panda260** [Barma-lej/halandroid#73]
![image](https://github.com/Barma-lej/halandroid/assets/52088459/2badaaec-59f4-47aa-b1ea-b1da06121ce2)

Firmware Update from the Landroid App Aktuelle Version: 3.2.8.0+1

**Comment by Barma-lej** [comment]
[Readme](https://github.com/Barma-lej/halandroid#dont-work-with-landroid-cloud--203)
